/**
 * 成都周边徒步登山线路词库（生成物，请勿手改）。
 *
 * 数据源：成都周边徒步登山线路表.xlsx，共 193 条线路。
 * 每条的 keys 是可用于标题模糊匹配的地名 / 山峰名中心词，由 scripts/extract-lines.js 提取。
 * 线路名称 / 星级 / 全长 / 爬升四项缺任何一项的线路（原表写「未知」的那几条）不入词库，
 * 所以这里的四项字段都是完整的，页面按它自动填，不需要空值兜底。
 *
 * 重新生成：node scripts/extract-lines.js
 */
const LINE_LIBRARY = [
  { id: 'line_001', name: '丁木沟', stars: 1, distance: 5.8, elevation: 600, keys: ['丁木沟'] },
  { id: 'line_002', name: '汶川望乡台', stars: 2, distance: 10.2, elevation: 1072, keys: ['汶川望乡台', '望乡台'] },
  { id: 'line_003', name: '小金大二岩三海子', stars: 3, distance: 11.2, elevation: 707, keys: ['小金大二岩三海子', '大二岩三海子'] },
  { id: 'line_004', name: '汶川巴朗山5072', stars: 4, distance: 7.5, elevation: 1257, keys: ['汶川巴朗山', '巴朗山'] },
  { id: 'line_005', name: '康定勒多曼日速穿', stars: 5, distance: 37, elevation: 1055, keys: ['康定勒多曼日', '勒多曼日'] },
  { id: 'line_006', name: '汶川迪斯穆斯科', stars: 5, distance: 13.1, elevation: 1483, keys: ['汶川迪斯穆斯科', '迪斯穆斯科'] },
  { id: 'line_007', name: '理县玉匹沟未央峰(主峰)', stars: 7, distance: 25.7, elevation: 2542, keys: ['理县玉匹沟未央峰', '玉匹沟未央峰', '玉匹沟'] },
  { id: 'line_008', name: '彭州/都江堰赵九铁单日加强版', stars: 7, distance: 45.7, elevation: 6354, keys: ['都江堰赵九铁', '赵九铁'] },
  { id: 'line_009', name: '纸坊沟', stars: 1, distance: 13.4, elevation: 354, keys: ['纸坊沟'] },
  { id: 'line_010', name: '泸定红岩顶', stars: 2, distance: 8.8, elevation: 968, keys: ['泸定红岩顶', '红岩顶'] },
  { id: 'line_011', name: '布拖县阿布泽鲁', stars: 3, distance: 15.7, elevation: 850, keys: ['布拖县阿布泽鲁', '阿布泽鲁'] },
  { id: 'line_012', name: '彭州铁瓦殿', stars: 4, distance: 15.8, elevation: 2097, keys: ['彭州铁瓦殿', '铁瓦殿'] },
  { id: 'line_013', name: '理县老君沟大沟子', stars: 5, distance: 29, elevation: 2000, keys: ['理县老君沟大沟子', '老君沟大沟子', '老君沟', '老君沟大沟'] },
  { id: 'line_014', name: '汶川大极石', stars: 5, distance: 16.4, elevation: 2165, keys: ['汶川大极石', '大极石'] },
  { id: 'line_015', name: '松潘七藏沟速穿', stars: 7, distance: 53.5, elevation: 2060, keys: ['松潘七藏沟', '七藏沟'] },
  { id: 'line_016', name: '汶川龙岩峰', stars: 7, distance: 32, elevation: 3800, keys: ['汶川龙岩峰', '龙岩峰'] },
  { id: 'line_017', name: '葛仙山小环线', stars: 1, distance: 9.65, elevation: 611, keys: ['葛仙山'] },
  { id: 'line_018', name: '大邑大邑千佛山环线', stars: 2, distance: 13.5, elevation: 837, keys: ['大邑千佛山', '千佛山'] },
  { id: 'line_019', name: '理县小马场', stars: 3, distance: 10.5, elevation: 1304, keys: ['理县小马场', '小马场'] },
  { id: 'line_020', name: '理县大马场牧场', stars: 4, distance: 16.9, elevation: 1568, keys: ['理县大马场牧场', '大马场牧场'] },
  { id: 'line_021', name: '小金梦笔山', stars: 5, distance: 28.4, elevation: 1346, keys: ['小金梦笔山', '梦笔山'] },
  { id: 'line_022', name: '泸定田海子4978', stars: 5, distance: 17, elevation: 944, keys: ['泸定田海子', '田海子'] },
  { id: 'line_023', name: '康定子龙移境速穿', stars: 7, distance: 44, elevation: 2035, keys: ['康定子龙移境', '子龙移境'] },
  { id: 'line_024', name: '彭州/都江堰油灌顶', stars: 7, distance: 36, elevation: 2300, keys: ['都江堰油灌顶', '油灌顶'] },
  { id: 'line_025', name: '邛崃皮缝古道环线', stars: 1, distance: 9.6, elevation: 404, keys: ['邛崃皮缝古道', '皮缝古道'] },
  { id: 'line_026', name: '都江堰青城后山环线', stars: 2, distance: 16.4, elevation: 913, keys: ['都江堰青城后山', '青城后山'] },
  { id: 'line_027', name: '茂县九顶山环线', stars: 3, distance: 16.1, elevation: 940, keys: ['茂县九顶山', '九顶山'] },
  { id: 'line_028', name: '小金结斯沟穿山洞', stars: 4, distance: 8.8, elevation: 1116, keys: ['小金结斯沟', '结斯沟'] },
  { id: 'line_029', name: '理县玉匹西长海子', stars: 5, distance: 24.5, elevation: 1808, keys: ['理县玉匹西长海子', '玉匹西长海子'] },
  { id: 'line_030', name: '汶川喜德/冕宁俄而则俄反穿', stars: 5, distance: 24, elevation: 1670, keys: ['汶川喜德', '喜德', '冕宁俄而则俄', '俄而则俄'] },
  { id: 'line_031', name: '泸定中山峰冰塔林', stars: 7, distance: 25.3, elevation: 3065, keys: ['泸定中山峰冰塔林', '中山峰冰塔林', '中山峰'] },
  { id: 'line_032', name: '茂县/彭州红照壁(仙人峰)', stars: 7, distance: 35, elevation: 3300, keys: ['彭州红照壁', '红照壁', '仙人峰'] },
  { id: 'line_033', name: '犍为桫椤大峡谷', stars: 1, distance: 10.6, elevation: 325, keys: ['犍为桫椤大峡谷', '桫椤大峡谷'] },
  { id: 'line_034', name: '都江堰铜马沟', stars: 2, distance: 13.6, elevation: 802, keys: ['都江堰铜马沟', '铜马沟'] },
  { id: 'line_035', name: '汶川巴朗山4688', stars: 3, distance: 8.1, elevation: 963, keys: ['汶川巴朗山', '巴朗山'] },
  { id: 'line_036', name: '理县九子屯笔架山', stars: 4, distance: 17.8, elevation: 1411, keys: ['理县九子屯笔架山', '九子屯笔架山'] },
  { id: 'line_037', name: '理县族那峰', stars: 5, distance: 11.8, elevation: 1970, keys: ['理县族那峰', '族那峰'] },
  { id: 'line_038', name: '汶川巴夺沟环线', stars: 5, distance: 20.2, elevation: 2140, keys: ['汶川巴夺沟', '巴夺沟'] },
  { id: 'line_039', name: '理县大乘山', stars: 7, distance: 18.3, elevation: 2650, keys: ['理县大乘山', '大乘山'] },
  { id: 'line_041', name: '大邑药师岩环线', stars: 1, distance: 10, elevation: 494, keys: ['大邑药师岩', '药师岩'] },
  { id: 'line_042', name: '理县纳山3800', stars: 2, distance: 8.3, elevation: 920, keys: ['理县纳山', '纳山'] },
  { id: 'line_043', name: '泸定上野马海子', stars: 3, distance: 9.76, elevation: 681, keys: ['泸定上野马海子', '上野马海子'] },
  { id: 'line_044', name: '汶川石谷垭口', stars: 4, distance: 13.7, elevation: 1794, keys: ['汶川石谷垭口', '石谷垭口'] },
  { id: 'line_045', name: '都江堰火烧杠', stars: 5, distance: 11.1, elevation: 1810, keys: ['都江堰火烧杠', '火烧杠'] },
  { id: 'line_046', name: '茂县狮子王', stars: 6, distance: 27.7, elevation: 2324, keys: ['茂县狮子王', '狮子王'] },
  { id: 'line_047', name: '小金汗牛斯古拉', stars: 7, distance: 35, elevation: 2979, keys: ['小金汗牛斯古拉', '汗牛斯古拉'] },
  { id: 'line_049', name: '彭州太阳湾', stars: 1, distance: 8.04, elevation: 510, keys: ['彭州太阳湾', '太阳湾'] },
  { id: 'line_050', name: '彭州狮子山大环线', stars: 2, distance: 11.9, elevation: 985, keys: ['彭州狮子山', '狮子山'] },
  { id: 'line_051', name: '理县纳窝牧场4100', stars: 3, distance: 9.8, elevation: 1110, keys: ['理县纳窝牧场', '纳窝牧场'] },
  { id: 'line_052', name: '理县小丘地牧场', stars: 4, distance: 14.6, elevation: 1624, keys: ['理县小丘地牧场', '小丘地牧场'] },
  { id: 'line_053', name: '理县后海子(非中转)', stars: 5, distance: 24.4, elevation: 2047, keys: ['理县后海子', '后海子'] },
  { id: 'line_054', name: '茂县太子城', stars: 6, distance: 29, elevation: 2047, keys: ['茂县太子城', '太子城'] },
  { id: 'line_055', name: '理县鱼海子小笼包5028', stars: 7, distance: 29.3, elevation: 2473, keys: ['理县鱼海子小笼包', '鱼海子小笼包', '鱼海子'] },
  { id: 'line_056', name: '理县尔尔若斯朵', stars: 8, distance: 29.9, elevation: 2645, keys: ['理县尔尔若斯朵', '尔尔若斯朵'] },
  { id: 'line_057', name: '汶川卧龙甘海子', stars: 1, distance: 7.4, elevation: 515, keys: ['汶川卧龙甘海子', '卧龙甘海子'] },
  { id: 'line_058', name: '崇州金凤山大环线', stars: 2, distance: 13.13, elevation: 770, keys: ['崇州金凤山', '金凤山'] },
  { id: 'line_059', name: '汶川猛古雪山3730', stars: 3, distance: 11.7, elevation: 1162, keys: ['汶川猛古雪山', '猛古雪山'] },
  { id: 'line_060', name: '彭州九峰山', stars: 4, distance: 14.4, elevation: 1910, keys: ['彭州九峰山', '九峰山'] },
  { id: 'line_061', name: '小金大峰(非雪季)', stars: 5, distance: 29.2, elevation: 1941, keys: ['小金大峰', '大峰'] },
  { id: 'line_062', name: '理县小乘山', stars: 6, distance: 16.2, elevation: 2586, keys: ['理县小乘山', '小乘山'] },
  { id: 'line_063', name: '彭州三口锅大二三四锅连登', stars: 7, distance: 23.7, elevation: 2975, keys: ['彭州三口锅大二三四锅', '三口锅大二三四锅', '三口锅'] },
  { id: 'line_064', name: '理县大小玛雅', stars: 8, distance: 19.5, elevation: 2407, keys: ['理县大小玛雅', '大小玛雅'] },
  { id: 'line_065', name: '理县厄尔娜沟', stars: 1, distance: 7, elevation: 405, keys: ['理县厄尔娜沟', '厄尔娜沟'] },
  { id: 'line_066', name: '彭州回龙沟', stars: 2, distance: 17.6, elevation: 690, keys: ['彭州回龙沟', '回龙沟'] },
  { id: 'line_067', name: '汶川海尔凼', stars: 3, distance: 7.54, elevation: 669, keys: ['汶川海尔凼', '海尔凼'] },
  { id: 'line_068', name: '汶川鸡公梁子', stars: 4, distance: 16.2, elevation: 1760, keys: ['汶川鸡公梁子', '鸡公梁子'] },
  { id: 'line_069', name: '理县大玛雅(近路)', stars: 5, distance: 9.7, elevation: 1702, keys: ['理县大玛雅', '大玛雅'] },
  { id: 'line_070', name: '泸定二层山', stars: 6, distance: 33.6, elevation: 2600, keys: ['泸定二层山', '二层山'] },
  { id: 'line_071', name: '茂县狮太连登(两日)', stars: 7, distance: 50, elevation: 3850, keys: ['茂县狮太', '狮太'] },
  { id: 'line_072', name: '峨眉山环线100公里', stars: 8, distance: 100, elevation: 4650, keys: ['峨眉山'] },
  { id: 'line_073', name: '彭州中坝森林大环线', stars: 1, distance: 8.6, elevation: 407, keys: ['彭州中坝森林', '中坝森林'] },
  { id: 'line_074', name: '大邑大小飞水穿越', stars: 2, distance: 13.1, elevation: 720, keys: ['大邑大小飞水', '大小飞水'] },
  { id: 'line_075', name: '汶川拉拉虎', stars: 3, distance: 10.7, elevation: 1256, keys: ['汶川拉拉虎', '拉拉虎'] },
  { id: 'line_076', name: '理县斯嘉依梁子', stars: 4, distance: 18, elevation: 1462, keys: ['理县斯嘉依梁子', '斯嘉依梁子'] },
  { id: 'line_077', name: '小金依央嘉波', stars: 5, distance: 15.1, elevation: 1366, keys: ['小金依央嘉波', '依央嘉波'] },
  { id: 'line_078', name: '汶川磨刀石三峰', stars: 6, distance: 20.8, elevation: 2742, keys: ['汶川磨刀石三峰', '磨刀石三峰'] },
  { id: 'line_079', name: '彭州/都江堰赵九铁单日', stars: 7, distance: 38, elevation: 5322, keys: ['都江堰赵九铁', '赵九铁'] },
  { id: 'line_080', name: '彭州青龙峰', stars: 8, distance: 20.3, elevation: 2866, keys: ['彭州青龙峰', '青龙峰'] },
  { id: 'line_081', name: '汶川巴朗山穿牛沟', stars: 1, distance: 8.5, elevation: 193, keys: ['汶川巴朗山', '巴朗山', '牛沟'] },
  { id: 'line_082', name: '崇州都统岩', stars: 2, distance: 10.2, elevation: 924, keys: ['崇州都统岩', '都统岩'] },
  { id: 'line_083', name: '汶川阿尔沟', stars: 3, distance: 10.55, elevation: 1099, keys: ['汶川阿尔沟', '阿尔沟'] },
  { id: 'line_084', name: '都江堰赵公山ABBA', stars: 4, distance: 12.4, elevation: 2023, keys: ['都江堰赵公山', '赵公山'] },
  { id: 'line_085', name: '泸定加米峰4520', stars: 5, distance: 26.5, elevation: 1927, keys: ['泸定加米峰', '加米峰'] },
  { id: 'line_086', name: '理县老君沟新海子', stars: 6, distance: 31.5, elevation: 2412, keys: ['理县老君沟新海子', '老君沟新海子', '老君沟'] },
  { id: 'line_087', name: '理县/茂县九龙池穿尔乌熟', stars: 7, distance: 30, elevation: 3100, keys: ['茂县九龙池', '九龙池', '尔乌熟'] },
  { id: 'line_088', name: '彭州白虎峰(多日)', stars: 8, distance: 52, elevation: 4370, keys: ['彭州白虎峰', '白虎峰'] },
  { id: 'line_089', name: '崇州琉璃坝', stars: 1, distance: 9, elevation: 466, keys: ['崇州琉璃坝', '琉璃坝'] },
  { id: 'line_090', name: '小金木尔寨沟', stars: 2, distance: 10.6, elevation: 218, keys: ['小金木尔寨沟', '木尔寨沟'] },
  { id: 'line_091', name: '理县十瀑海子', stars: 3, distance: 7.2, elevation: 924, keys: ['理县十瀑海子', '十瀑海子'] },
  { id: 'line_092', name: '汶川什达格', stars: 4, distance: 17.4, elevation: 1109, keys: ['汶川什达格', '什达格'] },
  { id: 'line_093', name: '理县希尔基斯朵', stars: 5, distance: 24, elevation: 1800, keys: ['理县希尔基斯朵', '希尔基斯朵'] },
  { id: 'line_094', name: '康定雅拉温泉线反穿', stars: 6, distance: 45, elevation: 1350, keys: ['康定雅拉温泉线', '雅拉温泉线'] },
  { id: 'line_095', name: '汶川领学峰', stars: 7, distance: 26, elevation: 3260, keys: ['汶川领学峰', '领学峰'] },
  { id: 'line_096', name: '彭州/茂县南坡太子城(多日)', stars: 8, distance: 48, elevation: 4200, keys: ['茂县南坡太子城', '太子城'] },
  { id: 'line_097', name: '大邑龙窝子往返', stars: 1, distance: 8.1, elevation: 557, keys: ['大邑龙窝子', '龙窝子'] },
  { id: 'line_098', name: '茂县浮云牧场至白空寺', stars: 2, distance: 7.1, elevation: 840, keys: ['茂县浮云牧场', '浮云牧场', '白空寺'] },
  { id: 'line_099', name: '汶川阿嘟雕', stars: 3, distance: 7.38, elevation: 1222, keys: ['汶川阿嘟雕', '阿嘟雕'] },
  { id: 'line_100', name: '乐山丁木沟高位线', stars: 4, distance: 20.1, elevation: 1180, keys: ['乐山丁木沟', '丁木沟'] },
  { id: 'line_101', name: '汶川幸福山4450', stars: 5, distance: 21, elevation: 2300, keys: ['汶川幸福山', '幸福山'] },
  { id: 'line_102', name: '理县红砂梁子垭口', stars: 6, distance: 20.8, elevation: 2270, keys: ['理县红砂梁子垭口', '红砂梁子垭口'] },
  { id: 'line_103', name: '茂县南天门', stars: 7, distance: 33.4, elevation: 2647, keys: ['茂县南天门', '南天门'] },
  { id: 'line_104', name: '彭州/茂县南坡太子城(多日)', stars: 9, distance: 48, elevation: 4200, keys: ['茂县南坡太子城', '太子城'] },
  { id: 'line_105', name: '都江堰蒲虹路穿越', stars: 1, distance: 10.1, elevation: 341, keys: ['都江堰蒲虹路', '蒲虹路'] },
  { id: 'line_106', name: '汶川云中岭', stars: 2, distance: 9, elevation: 772, keys: ['汶川云中岭', '云中岭'] },
  { id: 'line_107', name: '汶川/凉经泥巴山穿越大相岭', stars: 3, distance: 13.6, elevation: 1195, keys: ['凉经泥巴山', '泥巴山', '大相岭'] },
  { id: 'line_108', name: '理县猛古雪山4235', stars: 4, distance: 14.5, elevation: 1530, keys: ['理县猛古雪山', '猛古雪山'] },
  { id: 'line_109', name: '康定康定冰海子', stars: 5, distance: 17.4, elevation: 1856, keys: ['康定冰海子', '冰海子'] },
  { id: 'line_110', name: '理县甲尔主峰热嘎斗峰', stars: 6, distance: 23.5, elevation: 2665, keys: ['理县甲尔主峰热嘎斗峰', '甲尔主峰热嘎斗峰', '甲尔主峰'] },
  { id: 'line_111', name: '理县尔尔若斯朵', stars: 7, distance: 29.9, elevation: 2645, keys: ['理县尔尔若斯朵', '尔尔若斯朵'] },
  { id: 'line_112', name: '彭州元武峰(多日)', stars: 9, distance: 29, elevation: 4950, keys: ['彭州元武峰', '元武峰'] },
  { id: 'line_113', name: '龙泉驿钟家山百工堰环线', stars: 1, distance: 9.2, elevation: 370, keys: ['龙泉驿钟家山百工堰', '钟家山百工堰', '钟家山'] },
  { id: 'line_114', name: '乐山丁木沟中位瀑布线', stars: 2, distance: 12.7, elevation: 841, keys: ['乐山丁木沟', '丁木沟'] },
  { id: 'line_115', name: '邛崃南宝山连天峰', stars: 3, distance: 9.2, elevation: 1175, keys: ['邛崃南宝山连天峰', '南宝山连天峰', '南宝山'] },
  { id: 'line_116', name: '理县错青美洛', stars: 4, distance: 14.32, elevation: 800, keys: ['理县错青美洛', '错青美洛'] },
  { id: 'line_117', name: '理县麻里岗', stars: 5, distance: 18.4, elevation: 2160, keys: ['理县麻里岗', '麻里岗'] },
  { id: 'line_118', name: '小金鹰鸽嘴峰', stars: 6, distance: 29.3, elevation: 2096, keys: ['小金鹰鸽嘴峰', '鹰鸽嘴峰'] },
  { id: 'line_119', name: '理县大小玛雅', stars: 7, distance: 19.5, elevation: 2407, keys: ['理县大小玛雅', '大小玛雅'] },
  { id: 'line_120', name: '汶川/都江堰光光山(多日)', stars: 9, distance: 28, elevation: 3000, keys: ['都江堰光光山', '光光山'] },
  { id: 'line_121', name: '彭州石牛角', stars: 1, distance: 8, elevation: 407, keys: ['彭州石牛角', '石牛角'] },
  { id: 'line_122', name: '彭州虹口穿小鱼洞', stars: 2, distance: 12.1, elevation: 681, keys: ['彭州虹口', '虹口', '小鱼洞'] },
  { id: 'line_123', name: '泸定华尖山', stars: 3, distance: 12.2, elevation: 1078, keys: ['泸定华尖山', '华尖山'] },
  { id: 'line_124', name: '江油藏王寨大屋基环线', stars: 4, distance: 20.4, elevation: 1380, keys: ['江油藏王寨大屋基', '藏王寨大屋基'] },
  { id: 'line_125', name: '小金/理县长穿毕单日速穿', stars: 5, distance: 29, elevation: 1230, keys: ['理县长'] },
  { id: 'line_126', name: '彭州三口锅大锅', stars: 6, distance: 23.3, elevation: 2772, keys: ['彭州三口锅大锅', '三口锅大锅', '三口锅'] },
  { id: 'line_127', name: '峨眉山环线100公里', stars: 7, distance: 100, elevation: 4650, keys: ['峨眉山'] },
  { id: 'line_128', name: '汶川幸福山大板召石石班口', stars: 9, distance: 51.1, elevation: 6260, keys: ['汶川幸福山大板召石石班口', '幸福山大板召石石班口', '幸福山'] },
  { id: 'line_129', name: '金堂云顶山', stars: 1, distance: 9.2, elevation: 266, keys: ['金堂云顶山', '云顶山'] },
  { id: 'line_130', name: '泸定龙华山3000', stars: 2, distance: 5.7, elevation: 792, keys: ['泸定龙华山', '龙华山'] },
  { id: 'line_131', name: '都江堰赵公山东线', stars: 3, distance: 7.8, elevation: 1315, keys: ['都江堰赵公山', '赵公山'] },
  { id: 'line_132', name: '理县布勒牧场4395', stars: 4, distance: 11.5, elevation: 1312, keys: ['理县布勒牧场', '布勒牧场'] },
  { id: 'line_133', name: '峨眉山大沟穿万佛顶-金顶', stars: 5, distance: 18.1, elevation: 2350, keys: ['峨眉山大沟', '峨眉山', '万佛顶', '金顶'] },
  { id: 'line_134', name: '理县纳山4817峰', stars: 6, distance: 27, elevation: 2417, keys: ['理县纳山峰', '纳山峰'] },
  { id: 'line_135', name: '彭州青龙峰', stars: 7, distance: 20.3, elevation: 2866, keys: ['彭州青龙峰', '青龙峰'] },
  { id: 'line_136', name: '理县雪龙岭', stars: 9, distance: 31.2, elevation: 3820, keys: ['理县雪龙岭', '雪龙岭'] },
  { id: 'line_137', name: '金堂龚家山', stars: 1, distance: 9, elevation: 169, keys: ['金堂龚家山', '龚家山'] },
  { id: 'line_138', name: '都江堰上元古道', stars: 2, distance: 11.5, elevation: 705, keys: ['都江堰上元古道', '上元古道'] },
  { id: 'line_139', name: '汶川云上花林', stars: 3, distance: 9.8, elevation: 984, keys: ['汶川云上花林', '云上花林'] },
  { id: 'line_140', name: '黑水奥太娜', stars: 4, distance: 11, elevation: 1100, keys: ['黑水奥太娜', '奥太娜'] },
  { id: 'line_141', name: '小金九架海', stars: 5, distance: 20.8, elevation: 1472, keys: ['小金九架海', '九架海'] },
  { id: 'line_142', name: '汶川幸福山刀峰', stars: 6, distance: 26, elevation: 2650, keys: ['汶川幸福山刀峰', '幸福山刀峰', '幸福山'] },
  { id: 'line_143', name: '彭州白虎峰(多日)', stars: 7, distance: 52, elevation: 4370, keys: ['彭州白虎峰', '白虎峰'] },
  { id: 'line_144', name: '彭州/都江堰赵九铁单日加强版', stars: 9, distance: 45.7, elevation: 6354, keys: ['都江堰赵九铁', '赵九铁'] },
  { id: 'line_145', name: '汶川邓生沟', stars: 1, distance: 6.1, elevation: 123, keys: ['汶川邓生沟', '邓生沟'] },
  { id: 'line_146', name: '彭州彭州天台山', stars: 2, distance: 9.8, elevation: 880, keys: ['彭州天台山', '天台山'] },
  { id: 'line_147', name: '绵阳绵阳千佛山', stars: 3, distance: 12.9, elevation: 980, keys: ['绵阳千佛山', '千佛山'] },
  { id: 'line_148', name: '峨眉山马合湖穿万佛顶至金顶', stars: 4, distance: 21.5, elevation: 1368, keys: ['峨眉山马合湖', '马合湖', '峨眉山', '万佛顶', '金顶'] },
  { id: 'line_149', name: '茂县九顶后山', stars: 5, distance: 25.6, elevation: 2360, keys: ['茂县九顶后山', '九顶后山'] },
  { id: 'line_150', name: '彭州朱雀峰', stars: 6, distance: 21.9, elevation: 2813, keys: ['彭州朱雀峰', '朱雀峰'] },
  { id: 'line_151', name: '彭州/茂县南坡太子城(多日)', stars: 7, distance: 48, elevation: 4200, keys: ['茂县南坡太子城', '太子城'] },
  { id: 'line_152', name: '汶川龙岩峰', stars: 9, distance: 32, elevation: 3800, keys: ['汶川龙岩峰', '龙岩峰'] },
  { id: 'line_153', name: '大邑大飞水', stars: 1, distance: 7.2, elevation: 294, keys: ['大邑大飞水', '大飞水'] },
  { id: 'line_154', name: '汶川熊猫坪', stars: 2, distance: 9.2, elevation: 729, keys: ['汶川熊猫坪', '熊猫坪'] },
  { id: 'line_155', name: '大邑龙窝子环线', stars: 3, distance: 15.5, elevation: 840, keys: ['大邑龙窝子', '龙窝子'] },
  { id: 'line_156', name: '康定白海子', stars: 4, distance: 13.9, elevation: 1289, keys: ['康定白海子', '白海子'] },
  { id: 'line_157', name: '理县尽头峰', stars: 5, distance: 11.1, elevation: 1360, keys: ['理县尽头峰', '尽头峰'] },
  { id: 'line_158', name: '理县九龙江官山', stars: 6, distance: 18.2, elevation: 2656, keys: ['理县九龙江官山', '九龙江官山'] },
  { id: 'line_159', name: '彭州元武峰(多日)', stars: 7, distance: 29, elevation: 4950, keys: ['彭州元武峰', '元武峰'] },
  { id: 'line_160', name: '彭州/都江堰油灌顶', stars: 9, distance: 36, elevation: 2300, keys: ['都江堰油灌顶', '油灌顶'] },
  { id: 'line_161', name: '大邑白岩寺', stars: 1, distance: 4.9, elevation: 391, keys: ['大邑白岩寺', '白岩寺'] },
  { id: 'line_162', name: '大邑雾中山光明顶', stars: 2, distance: 8.1, elevation: 868, keys: ['大邑雾中山光明顶', '雾中山光明顶', '雾中山'] },
  { id: 'line_163', name: '都江堰云华山大环线', stars: 3, distance: 14.7, elevation: 1039, keys: ['都江堰云华山', '云华山'] },
  { id: 'line_164', name: '乐山大瓦山', stars: 4, distance: 13.1, elevation: 1379, keys: ['乐山大瓦山', '大瓦山'] },
  { id: 'line_165', name: '彭州火焰峰', stars: 5, distance: 17.74, elevation: 2175, keys: ['彭州火焰峰', '火焰峰'] },
  { id: 'line_166', name: '理县魔戒峰', stars: 6, distance: 12.3, elevation: 1796, keys: ['理县魔戒峰', '魔戒峰'] },
  { id: 'line_167', name: '汶川/都江堰光光山(多日)', stars: 7, distance: 28, elevation: 3000, keys: ['都江堰光光山', '光光山'] },
  { id: 'line_168', name: '茂县/彭州红照壁(仙人峰)', stars: 10, distance: 35, elevation: 3300, keys: ['彭州红照壁', '红照壁', '仙人峰'] },
  { id: 'line_169', name: '汶川老鸦山', stars: 1, distance: 4.3, elevation: 350, keys: ['汶川老鸦山', '老鸦山'] },
  { id: 'line_170', name: '都江堰松茂古道', stars: 2, distance: 9.3, elevation: 830, keys: ['都江堰松茂古道', '松茂古道'] },
  { id: 'line_171', name: '汶川熊猫之眼', stars: 3, distance: 7.8, elevation: 734, keys: ['汶川熊猫之眼', '熊猫之眼'] },
  { id: 'line_172', name: '理县纳窝穿夹嘎梁子至沙坝', stars: 5, distance: 25, elevation: 1935, keys: ['理县纳窝', '纳窝', '夹嘎梁子', '沙坝'] },
  { id: 'line_173', name: '汶川嘛咪堆堆', stars: 6, distance: 21.3, elevation: 2582, keys: ['汶川嘛咪堆堆', '嘛咪堆堆'] },
  { id: 'line_174', name: '汶川幸福山大板召石石班口', stars: 7, distance: 51.1, elevation: 6260, keys: ['汶川幸福山大板召石石班口', '幸福山大板召石石班口', '幸福山'] },
  { id: 'line_176', name: '理县九子屯', stars: 1, distance: 5, elevation: 221, keys: ['理县九子屯', '九子屯'] },
  { id: 'line_177', name: '龙泉驿仰天窝穿石经寺', stars: 2, distance: 14.3, elevation: 566, keys: ['龙泉驿仰天窝', '仰天窝', '石经寺'] },
  { id: 'line_178', name: '理县胆扎木左峰', stars: 3, distance: 18.6, elevation: 1595, keys: ['理县胆扎木左峰', '胆扎木左峰'] },
  { id: 'line_179', name: '松潘阿尼玛东穿海金沟', stars: 5, distance: 20.3, elevation: 1900, keys: ['松潘阿尼玛东', '阿尼玛东', '海金沟'] },
  { id: 'line_180', name: '康定扬扬拉措(九海子)', stars: 6, distance: 26.6, elevation: 2400, keys: ['康定扬扬拉措', '扬扬拉措', '九海子'] },
  { id: 'line_181', name: '理县雪龙岭', stars: 7, distance: 31.2, elevation: 3820, keys: ['理县雪龙岭', '雪龙岭'] },
  { id: 'line_183', name: '理县二古溪', stars: 1, distance: 4.6, elevation: 381, keys: ['理县二古溪', '二古溪'] },
  { id: 'line_184', name: '大邑鹤鸣山', stars: 2, distance: 8.9, elevation: 733, keys: ['大邑鹤鸣山', '鹤鸣山'] },
  { id: 'line_185', name: '理县甲尔猛措', stars: 3, distance: 17.5, elevation: 1756, keys: ['理县甲尔猛措', '甲尔猛措'] },
  { id: 'line_186', name: '汶川天鹅抱蛋环线', stars: 5, distance: 17, elevation: 1760, keys: ['汶川天鹅抱蛋', '天鹅抱蛋'] },
  { id: 'line_187', name: '汶川大板召4600', stars: 6, distance: 20.3, elevation: 2610, keys: ['汶川大板召', '大板召'] },
  { id: 'line_188', name: '汶川西羌大峡谷', stars: 2, distance: 11, elevation: 464, keys: ['汶川西羌大峡谷', '西羌大峡谷'] },
  { id: 'line_189', name: '都江堰青城前山', stars: 2, distance: 12.1, elevation: 555, keys: ['都江堰青城前山', '青城前山'] },
  { id: 'line_190', name: '理县纳山4485', stars: 3, distance: 17.7, elevation: 1595, keys: ['理县纳山', '纳山'] },
  { id: 'line_191', name: '泸定龙华山4155', stars: 5, distance: 18.3, elevation: 1938, keys: ['泸定龙华山', '龙华山'] },
  { id: 'line_192', name: '汶川盘龙山', stars: 6, distance: 26.2, elevation: 2867, keys: ['汶川盘龙山', '盘龙山'] },
  { id: 'line_193', name: '彭州法藏寺八步坎', stars: 2, distance: 11.3, elevation: 370, keys: ['彭州法藏寺八步坎', '法藏寺八步坎'] },
  { id: 'line_194', name: '什邡天鹅林场大环线', stars: 2, distance: 11.9, elevation: 627, keys: ['什邡天鹅林场', '天鹅林场'] },
  { id: 'line_195', name: '小金五人同', stars: 5, distance: 15.9, elevation: 1589, keys: ['小金五人同', '五人同'] },
  { id: 'line_196', name: '彭州马鬃岭', stars: 6, distance: 14.3, elevation: 2116, keys: ['彭州马鬃岭', '马鬃岭'] },
  { id: 'line_197', name: '昭觉县慧雄村', stars: 2, distance: 5, elevation: 850, keys: ['昭觉县慧雄村', '慧雄村'] },
]

/** 词库版本（内容哈希）：数据改了版本就变，用于判断本地缓存是否要刷新 */
const LINE_LIBRARY_VERSION = '3c783407'

module.exports = { LINE_LIBRARY, LINE_LIBRARY_VERSION }
